[2021-04-23 20:50:31,829] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T18:00:00+00:00 [queued]>
[2021-04-23 20:50:31,879] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T18:00:00+00:00 [queued]>
[2021-04-23 20:50:31,882] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 20:50:31,884] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-23 20:50:31,887] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 20:50:31,909] {taskinstance.py:1063} INFO - Executing <Task(PatchedDataprocDeleteClusterOperator): delete_cluster_dataproc> on 2021-04-23T18:00:00+00:00
[2021-04-23 20:50:31,921] {standard_task_runner.py:52} INFO - Started process 628 to run task
[2021-04-23 20:50:31,931] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'delete_cluster_dataproc', '2021-04-23T18:00:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmprp9xpqqm', '--error-file', '/tmp/tmpyafirszp']
[2021-04-23 20:50:31,940] {standard_task_runner.py:77} INFO - Job 41: Subtask delete_cluster_dataproc
[2021-04-23 20:50:32,051] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T18:00:00+00:00 [running]> on host 760ffd3d790b
[2021-04-23 20:50:32,138] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=delete_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-23T18:00:00+00:00
[2021-04-23 20:50:32,157] {dataproc.py:840} INFO - Deleting cluster: ephemeral-recent-played-spark-cluster-20210423
[2021-04-23 20:51:14,018] {dataproc.py:852} INFO - Cluster deleted.
[2021-04-23 20:51:15,151] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=delete_cluster_dataproc, execution_date=20210423T180000, start_date=20210423T205031, end_date=20210423T205115
[2021-04-23 20:51:17,559] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-23 20:51:19,582] {local_task_job.py:146} INFO - Task exited with return code 0
