[2021-04-25 13:00:01,728] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T12:00:00+00:00 [queued]>
[2021-04-25 13:00:01,777] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T12:00:00+00:00 [queued]>
[2021-04-25 13:00:01,779] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 13:00:01,780] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-25 13:00:01,781] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 13:00:01,794] {taskinstance.py:1063} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc> on 2021-04-25T12:00:00+00:00
[2021-04-25 13:00:01,801] {standard_task_runner.py:52} INFO - Started process 1051 to run task
[2021-04-25 13:00:01,806] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'create_cluster_dataproc', '2021-04-25T12:00:00+00:00', '--job-id', '100', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmp74qo74if', '--error-file', '/tmp/tmpdrotde04']
[2021-04-25 13:00:01,811] {standard_task_runner.py:77} INFO - Job 100: Subtask create_cluster_dataproc
[2021-04-25 13:00:01,894] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T12:00:00+00:00 [running]> on host 67976f37379c
[2021-04-25 13:00:02,003] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T12:00:00+00:00
[2021-04-25 13:00:02,006] {dataproc.py:603} INFO - Creating cluster: ephemeral-recent-played-spark-cluster-20210425
[2021-04-25 13:00:03,822] {dataproc.py:611} INFO - Cluster already exists.
[2021-04-25 13:00:04,220] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=create_cluster_dataproc, execution_date=20210425T120000, start_date=20210425T130001, end_date=20210425T130004
[2021-04-25 13:00:04,296] {local_task_job.py:146} INFO - Task exited with return code 1
