[2021-04-23 16:56:47,563] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T15:00:00+00:00 [queued]>
[2021-04-23 16:56:47,590] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T15:00:00+00:00 [queued]>
[2021-04-23 16:56:47,591] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 16:56:47,592] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2021-04-23 16:56:47,595] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 16:56:47,631] {taskinstance.py:1063} INFO - Executing <Task(PatchedDataprocDeleteClusterOperator): delete_cluster_dataproc> on 2021-04-23T15:00:00+00:00
[2021-04-23 16:56:47,640] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2021-04-23 16:56:47,646] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'delete_cluster_dataproc', '2021-04-23T15:00:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmpbla6z8hx', '--error-file', '/tmp/tmpxgaw4l8v']
[2021-04-23 16:56:47,651] {standard_task_runner.py:77} INFO - Job 18: Subtask delete_cluster_dataproc
[2021-04-23 16:56:47,748] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T15:00:00+00:00 [running]> on host 760ffd3d790b
[2021-04-23 16:56:47,815] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=delete_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T15:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-23T15:00:00+00:00
[2021-04-23 16:56:47,836] {dataproc.py:840} INFO - Deleting cluster: ephemeral-recent-played-spark-cluster-20210423
[2021-04-23 16:57:29,227] {dataproc.py:852} INFO - Cluster deleted.
[2021-04-23 16:57:29,252] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=delete_cluster_dataproc, execution_date=20210423T150000, start_date=20210423T165647, end_date=20210423T165729
[2021-04-23 16:57:29,304] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-23 16:57:29,352] {local_task_job.py:146} INFO - Task exited with return code 0
