[2021-04-25 14:00:02,150] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T13:00:00+00:00 [queued]>
[2021-04-25 14:00:02,192] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T13:00:00+00:00 [queued]>
[2021-04-25 14:00:02,193] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 14:00:02,195] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-25 14:00:02,196] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 14:00:02,208] {taskinstance.py:1063} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster_dataproc> on 2021-04-25T13:00:00+00:00
[2021-04-25 14:00:02,217] {standard_task_runner.py:52} INFO - Started process 1329 to run task
[2021-04-25 14:00:02,223] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'create_cluster_dataproc', '2021-04-25T13:00:00+00:00', '--job-id', '109', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmp5by4vx0x', '--error-file', '/tmp/tmp8z_ck4nx']
[2021-04-25 14:00:02,226] {standard_task_runner.py:77} INFO - Job 109: Subtask create_cluster_dataproc
[2021-04-25 14:00:02,281] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.create_cluster_dataproc 2021-04-25T13:00:00+00:00 [running]> on host 67976f37379c
[2021-04-25 14:00:02,380] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=create_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T13:00:00+00:00
[2021-04-25 14:00:02,398] {dataproc.py:603} INFO - Creating cluster: ephemeral-recent-played-spark-cluster-20210425
[2021-04-25 14:00:05,127] {dataproc.py:611} INFO - Cluster already exists.
[2021-04-25 14:00:05,555] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=create_cluster_dataproc, execution_date=20210425T130000, start_date=20210425T140002, end_date=20210425T140005
[2021-04-25 14:00:05,700] {local_task_job.py:146} INFO - Task exited with return code 1
