[2021-04-23 17:44:26,520] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T16:00:00+00:00 [queued]>
[2021-04-23 17:44:26,558] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T16:00:00+00:00 [queued]>
[2021-04-23 17:44:26,560] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 17:44:26,561] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2021-04-23 17:44:26,562] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 17:44:26,593] {taskinstance.py:1063} INFO - Executing <Task(PatchedDataprocDeleteClusterOperator): delete_cluster_dataproc> on 2021-04-23T16:00:00+00:00
[2021-04-23 17:44:26,601] {standard_task_runner.py:52} INFO - Started process 387 to run task
[2021-04-23 17:44:26,614] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'delete_cluster_dataproc', '2021-04-23T16:00:00+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmp8ki95xe4', '--error-file', '/tmp/tmpelkqs4_a']
[2021-04-23 17:44:26,626] {standard_task_runner.py:77} INFO - Job 32: Subtask delete_cluster_dataproc
[2021-04-23 17:44:26,742] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.delete_cluster_dataproc 2021-04-23T16:00:00+00:00 [running]> on host 760ffd3d790b
[2021-04-23 17:44:26,826] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=delete_cluster_dataproc
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T16:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-23T16:00:00+00:00
[2021-04-23 17:44:26,841] {dataproc.py:840} INFO - Deleting cluster: ephemeral-recent-played-spark-cluster-20210423
[2021-04-23 17:45:08,464] {dataproc.py:852} INFO - Cluster deleted.
[2021-04-23 17:45:08,654] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=recent_played_ingestion, task_id=delete_cluster_dataproc, execution_date=20210423T160000, start_date=20210423T174426, end_date=20210423T174508
[2021-04-23 17:45:08,794] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-23 17:45:09,009] {local_task_job.py:146} INFO - Task exited with return code 0
