[2021-04-25 10:44:42,386] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.run_recent_played_ingestion_pypark 2021-04-25T09:00:00+00:00 [queued]>
[2021-04-25 10:44:42,414] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.run_recent_played_ingestion_pypark 2021-04-25T09:00:00+00:00 [queued]>
[2021-04-25 10:44:42,415] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 10:44:42,416] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2021-04-25 10:44:42,417] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 10:44:42,426] {taskinstance.py:1063} INFO - Executing <Task(DataprocSubmitPySparkJobOperator): run_recent_played_ingestion_pypark> on 2021-04-25T09:00:00+00:00
[2021-04-25 10:44:42,431] {standard_task_runner.py:52} INFO - Started process 353 to run task
[2021-04-25 10:44:42,435] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'run_recent_played_ingestion_pypark', '2021-04-25T09:00:00+00:00', '--job-id', '71', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmppio27z5r', '--error-file', '/tmp/tmpgjbux6lb']
[2021-04-25 10:44:42,439] {standard_task_runner.py:77} INFO - Job 71: Subtask run_recent_played_ingestion_pypark
[2021-04-25 10:44:42,499] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.run_recent_played_ingestion_pypark 2021-04-25T09:00:00+00:00 [running]> on host 67976f37379c
[2021-04-25 10:44:42,555] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=run_recent_played_ingestion_pypark
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T09:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T09:00:00+00:00
[2021-04-25 10:44:42,557] {dataproc.py:981} INFO - Submitting pyspark_job job run_recent_played_ingestion_pypark_20210425_1a278485
[2021-04-25 10:44:43,097] {dataproc.py:986} INFO - Job run_recent_played_ingestion_pypark_20210425_1a278485 submitted successfully.
[2021-04-25 10:44:43,098] {dataproc.py:989} INFO - Waiting for job run_recent_played_ingestion_pypark_20210425_1a278485 to complete
[2021-04-25 10:45:02,683] {local_task_job.py:188} WARNING - State of this instance has been externally set to shutdown. Terminating instance.
[2021-04-25 10:45:02,699] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 353
[2021-04-25 10:45:02,701] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-25 10:45:03,053] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 1545, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 990, in execute
    self.hook.wait_for_job(job_id=job_id, location=self.region, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 726, in wait_for_job
    time.sleep(wait_time)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-25 10:45:03,059] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=recent_played_ingestion, task_id=run_recent_played_ingestion_pypark, execution_date=20210425T090000, start_date=20210425T104442, end_date=20210425T104503
[2021-04-25 10:45:03,121] {process_utils.py:66} INFO - Process psutil.Process(pid=353, status='terminated', exitcode=1, started='10:44:41') (353) terminated with exit code 1
